### ISSUE TITLE
Contact plugin update for ver. 3.0.0

### ISSUE THREAD

**Issue by vikgor** [Fred89/bludit-plugins#17]
Hi! The Contact plugin is awesome but since I moved to version 3.0.0 it (obviously) stopped worling. 
Would be great if you could find some time to update it to 3.0.0
Thanks!

**Comment by lupinehorror** [comment]
i second the above...it'd be great if it were supported on v3

**Comment by vikgor** [comment]
> i second the above...it'd be great if it were supported on v3

Actually, they just made a new one, for the v.3: https://plugins.bludit.com/plugin/contact3
(if the link gets deleted - go to the official Bludit plugins website, Contact3 is what you're looking for)
